name: promote
on: 
  workflow_dispatch:
    inputs:
      version:
        description: filePath
        default: versions.json
        required: true

env:
  TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.TF_CLOUD_TOKEN }}

jobs:
  version:
    name: Get Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Show Version
        run: echo ${{ github.event.inputs.version }}
      - name: "Read file contents"
        uses: andstor/file-reader-action@v1
        with:
          path: "versions.json"
      - name: SHow file contents
        run: echo "${ steps.read_file.outputs.contents }"
