name: promote
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true

env:
  TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.TF_CLOUD_TOKEN }}

jobs:
  version:
    name: Get Version
    runs-on: ubuntu-latest
    steps:
      - name: SHow Version
        run: echo ${{ github.event.inputs.version }}
      - name: Read versions.json
        id: versions
        uses: juliangruber/read-file-action@v1
        with:
          path: ./versions.json
      - name: Echo versions.json
        run: echo "${{ steps.versions.outputs.content }}"
