name: promote
on: 
  workflow_dispatch:
    inputs:
      component:
        description: component
        default: edjapi
        required: true
      version:
        description: version
        default: 1.0.0
        required: true
      file:
        description: file
        default: versions.yaml
        required: true

env:
  TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.TF_CLOUD_TOKEN }}

jobs:
  version:
    name: Get Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Show Version
        run: echo ${{ github.event.inputs.version }}
      - name: Show File
        run: echo ${{ github.event.inputs.file }}
      - name: Update Versions
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: ${{ github.event.inputs.file }}
          propertyPath: ${{ github.event.inputs.component }}
          value: ${{ github.event.inputs.version }}
          commitChange: true
          message: 'CI Update Version'
          updateFile: true
      - name: "Read file contents"
        id: file
        uses: andstor/file-reader-action@v1
        with:
          path: ${{ github.event.inputs.file }}