name: promote
on: 
  workflow_dispatch:
    inputs:
      component:
        description: component
        default: edjapi
        required: true
      version:
        description: version
        default: 1.0.0
        required: true
      file:
        description: file
        default: versions.yaml
        required: true

jobs:
  version:
    name: Get Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Show Version
        run: echo ${{ github.event.inputs.version }}
      - name: Show File
        run: echo ${{ github.event.inputs.file }}
      - name: Update Versions
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: ${{ github.event.inputs.file }}
          propertyPath: ${{ github.event.inputs.component }}
          value: ${{ github.event.inputs.version }}
          commitChange: true
          branch: main 
          targetBranch: main
          message: 'CI Update Version'
          updateFile: true
      - name: Read Versions
        uses: CumulusDS/get-yaml-paths-action@v0.1.0
        with:
          file: ${{ github.event.inputs.file }}
          api: edjapi
          console: edjconsole
