name: Update Version

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Versions
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'versions.yaml'
          propertyPath: 'edjapi'
          value: v1.0.1
          commitChange: true
          message: 'CI Update Version'
          updateFile: true